function opt = initprocopt()
% ==================================================================================================
% INITPROCOPT
%   initialize processing options struct
% ==================================================================================================

global const

opt.posmode     = const.POSMODE_SINGLE; % Positioning mode (POSMODE_?)
opt.soltype     = 0; % Solution type (0: forward | 1: backward | 2: combined)
opt.nfreq       = 1; % Number of frequency
opt.navsys      = 'G'; % Navigation system (G: GPS | R: GLONASS | E: Galileo | J: QZSS | C: BDS | I: IRNSS | S: SBAS)
opt.elmask      = 10*const.DEG2RAD; % Elevation mask angle [deg]
opt.snrmask     = []; % SNR mask
opt.eph         = const.EPHOPT_BRDC; % Satellite ephemeris and clock option (EPHOPT_?)
opt.armode      = const.ARMODE_CONT; % AR (Ambiguity Resolution) mode (ARMODE_?)
opt.gloarmode   = const.GLOARMODE_ON; % GLONASS AR mode (GLOARMODE_?)
opt.galarmode   = 1; % Galileo AR mode (0: off | 1: on)
opt.bdsarmode   = 1; % BDS AR mode (0: off | 1: on)
opt.qzrarmode   = 1; % QZSS AR mode (0: off | 1: on)
opt.maxout      = 5; % Maximum outage count to reset phase bias
opt.minlock     = 20; % Minimum number of lock counts to fix ambiguity
opt.minfix      = 20; % Minimum number of fix counts to hold ambiguity
opt.maxariter   = 1; % Maximum number of iterations to resolve ambiguity
opt.iono        = const.IONOOPT_OFF; % Ionosphere option (IONOOPT_?)
opt.tropo       = const.TROPOOPT_OFF; % Troposphere option (TROPOOPT_?)
opt.tidecorr    = 0; % Earth tide correction option (0: off | 1: solid | 2: solid+OTL+pole)
opt.niter       = 1; % Number of filter iterations
opt.codesmooth  = 0; % Code smoothing window size (0: none)
opt.interpbase  = 0; % Interpolate base observation (for post mission)
opt.sbasopt     = 0; % SBAS correction option
opt.sbassatsel  = 0; % SBAS satellite selection (0: all)
opt.rovpostype  = const.POSTYPE_RINEX; % Rover position option for fixed mode
opt.basepostype = const.POSTYPE_RINEX; % Base position option for relative mode (POSTYPE_???)
opt.errratio    = [100, 100, 100, 100, 100]; % Code/phase error ratio
opt.err         = [100, 0.003, 0.003, 0, 1]; % Measurement error factor
opt.initstd     = [30, 0.03, 0.3]; % Standard deviation of initial state
opt.procnoise   = [1E-4, 1E-3, 1E-4, 1E-1, 1E-2, 0.0]; % Standard deviation of process noise
opt.satclkstab  = 5E-12; % Satellite clock stability [s/s]
opt.arthres     = [3.0, 0.25, 0, 1E-9, 1E-5, 0, 0, 0]; % AR validation threshold
opt.elmaskar    = 15*const.DEG2RAD; % Elevation mask angle for rising satellite [deg]
opt.elmaskhold  = 15*const.DEG2RAD; % Elevation mask angle to hold ambiguity [deg]
opt.slipthres   = 0.05; % Cycle slip threshold of geometry-free phase [m]
opt.maxage      = 30; % Maximum age of diffrential [s]
opt.maxinno     = 30; % Rejection threshold of innovation [m]
opt.maxgdop     = 30; % Rejection threshold of GDOP
opt.baseline    = [0, 0]; % Baseline length constraint [m]
opt.rr          = [0, 0, 0]; % Rover position for fixed mode (ECEF) [m]
opt.rb          = [0, 0, 0]; % Base position for relative mode (CEF) [m]
opt.anttype     = {''; '*'}; % Antenna type
opt.antdel      = repmat({zeros(1, 3)}, 2, 1); % Antenna delta (e/n/u) [m]
opt.pcvr        = initpcv(2); % Receiver antenna paramters
opt.exsats      = zeros(const.MAX_SAT, 1); % Excluded or included satellites (1: excluded | 2: included)
opt.maxavgep    = 0; % Maximum number of averaging epochs
opt.initrst     = 0; % Initialize by restart
opt.outsingle   = 0; % Output SPP solution by DGPS / RTK float / RTK fix / PPP outage
opt.rnxopt      = ''; % RINEX options
opt.posopt      = [0, 1, 0, 0, 0, 0]; % Positioning options
opt.syncsol     = 0; % Solution synchronization mode (0: off | 1: on)
opt.otl         = repmat({zeros(6, 11)}, 2, 1); % Ocean tide loading parameters
opt.freqopt     = 0; % Disable L2 AR
opt.pppopt      = ''; % PPP option

% default options ----------------------------------------------------------------------------------
function opt = defopt

opt.posmode     = const.POSMODE_SINGLE; % Positioning mode (POSMODE_?)
opt.soltype     = 0; % Solution type (0: forward | 1: backward | 2: combined)
opt.nfreq       = 1; % Number of frequency
opt.navsys      = 'G'; % Navigation system (G: GPS | R: GLONASS | E: Galileo | J: QZSS | C: BDS | I: IRNSS | S: SBAS)
opt.elmask      = 10 * pi / 180; % Elevation mask angle [deg]
opt.snrmask     = []; % SNR mask
opt.eph         = const.EPHOPT_BRDC; % Satellite ephemeris and clock option (EPHOPT_?)
opt.armode      = const.ARMODE_CONT; % AR (Ambiguity Resolution) mode (ARMODE_?)
opt.gloarmode   = const.GLOARMODE_ON; % GLONASS AR mode
opt.galarmode   = 1; % Galileo AR mode
opt.bdsarmode   = 1; % BDS AR mode
opt.maxout      = 5; % Maximum outage count to reset phase bias
opt.minlock     = 20; % Minimum number of lock counts to fix ambiguity
opt.minfix      = 20; % Minimum number of fix counts to hold ambiguity
opt.maxariter   = 1; % Maximum number of iterations to resolve ambiguity
opt.iono        = const.IONOOPT_OFF; % Ionosphere option (IONOOPT_?)
opt.tropo       = const.TROPOOPT_OFF; % Troposphere option (TROPOOPT_?)
opt.dynamics    = 0; % Receiver dynamic model (0: none | 1: velocity | 2: acceleration)
opt.tidecorr    = 0; % Earth tide correction option (0: off | 1: solid | 2: solid+OTL+pole)
opt.niter       = 1; % Number of filter iterations
opt.codesmooth  = 0; % Code smoothing window size (0: none)
opt.interpbase  = 0; % Interpolate base observation (for post mission)
opt.sbasopt     = 0; % SBAS correction option
opt.sbassatsel  = 0; % SBAS satellite selection (0: all)
opt.rovpostype  = 0; % Rover position option for fixed mode
opt.basepostype = 3; % Base position option for relative mode (0: position in 'procopt' | 1: average of SPP solutions | 2: read from file | 3: RINEX | 4: RTCM)
opt.eratio      = [100, 100, 100, 100, 100]; % Code/phase error ratio
opt.err         = [100, 0.003, 0.003, 0, 1]; % Measurement error factor
opt.initstd     = [30, 0.03, 0.3]; % Standard deviation of initial state
opt.procnoise   = [1E-4, 1E-3, 1E-4, 1E-1, 1E-2, 0.0]; % Standard deviation of process noise
opt.satclkstab  = 5E-12; % Satellite clock stability [s/s]
opt.arthres     = [3.0, 0.9999, 0.25, 0.1, 0.05, 0, 0, 0]; % AR validation threshold
opt.elmaskar    = 15 * pi / 180; % Elevation mask angle for rising satellite [deg]
opt.elmaskhold  = 15 * pi / 180; % Elevation mask angle to hold ambiguity [deg]
opt.slipthres    = 0.05; % Cycle slip threshold of geometry-free phase [m]
opt.maxage      = 30; % Maximum age of diffrential [s]
opt.maxinno     = 30; % Rejection threshold of innovation [m]
opt.maxgdop     = 30; % Rejection threshold of GDOP
opt.baseline    = [0, 0]; % Baseline length constraint [m]
opt.rr          = [0, 0, 0]; % Rover position for fixed mode (ECEF) [m]
opt.rb          = [0, 0, 0]; % Base position for relative mode (CEF) [m]
opt.anttype     = {'*'; '*'}; % Antenna type
opt.antdel      = repmat({zeros(1, 3)}, 2, 1); % Antenna delta (e/n/u) [m]
opt.pcvr        = initpcv(2); % Receiver antenna paramters
opt.exsats      = zeros(const.MAX_SAT, 1); % Excluded or included satellites (1: excluded | 2: included)
opt.maxavgep    = 0; % Maximum number of averaging epochs
opt.initrst     = 0; % Initialize by restart
opt.outsingle   = 0; % Output SPP solution by DGPS / RTK float / RTK fix / PPP outage
opt.rnxopt      = ''; % RINEX options
opt.posopt      = [0, 0, 0, 0, 0, 0]; % Positioning options
opt.syncsol     = 0; % Solution synchronization mode (0: off | 1: on)
opt.otl         = repmat({zeros(6, 11)}, 2, 1); % Ocean tide loading parameters
opt.freqopt     = 0; % Disable L2 AR
opt.pppopt      = '';